### ISSUE TITLE
서버 설정

### ISSUE THREAD

**Issue by do02reen24** [boostcamp-2020/IssueTracker-08#2]
# 백엔드, 프론트 서버 생성
1. ncloud 로그인
2. 서버 생성
![image](https://user-images.githubusercontent.com/50297117/97251683-ab456e00-184b-11eb-9998-24f064167048.png)
![image](https://user-images.githubusercontent.com/50297117/97251784-e2b41a80-184b-11eb-983d-3774b96be754.png)
* 우분투 버전 16
3. 인증키 생성
![image](https://user-images.githubusercontent.com/50297117/97251842-037c7000-184c-11eb-951b-282c73f03e45.png)
4. ACG 생성
![image](https://user-images.githubusercontent.com/50297117/97252259-ed22e400-184c-11eb-8a89-3a34556d7896.png)
5. 공인 IP 설정
![image](https://user-images.githubusercontent.com/50297117/97252743-1001c800-184e-11eb-8063-11d3602ca269.png)
6. 최초 접속 후 우분투 패키지 업그레이드 및 한글 설정
``` bash
$ sudo apt-get update
$ sudo apt-get upgrade
$ sudo apt-get install language-pack-ko
$ sudo locale-gen ko_KR.UTF-8
```
7. 한글 로케일 설정
```bash
$ locale
$ sudo -i
$ cat << 'EOF' > /etc/default/locale
LANG="ko_KR.UTF-8"
LANGUAGE="ko_KR:ko:en_US:en"
EOF

bash 재시작 (혹은 ubuntu 재부팅) 후 확인
locale
```
8. mysql 설치
```bash
$ apt install mysql-server
-> id: root / pw: root
$ sudo systemctl start mysql

DB 정상 설치 확인
$ mysql -u root -p
=> 정상 접속 확인
````
9. msyql utf-8 설정
```bash
$ cat /etc/mysql/my.cnf
$ cat << 'EOF' > /etc/mysql/mysql.conf.d/utf8.cnf
# for utf8 characterset
[client]
default-character-set = utf8

[mysqld]
init_connect = SET collation_connection = utf8_general_ci
init_connect = SET NAMES utf8
character-set-server = utf8
collation-server = utf8_general_ci

[mysqldump]
default-character-set = utf8

[mysql]
default-character-set = utf8
EOF

$ systemctl restart mysql
$ mysql -u root -p

- characterset uft8로 변경된 것 확인 (완료)
mysql> status
--------------
mysql  Ver 14.14 Distrib 5.7.31, for Linux (x86_64) using  EditLine wrapper

Connection id:          3
Current database:
Current user:           root@localhost
SSL:                    Not in use
Current pager:          stdout
Using outfile:          ''
Using delimiter:        ;
Server version:         5.7.31-0ubuntu0.16.04.1 (Ubuntu)
Protocol version:       10
Connection:             Localhost via UNIX socket
Server characterset:    utf8
Db     characterset:    utf8
Client characterset:    utf8
Conn.  characterset:    utf8
UNIX socket:            /var/run/mysqld/mysqld.sock
Uptime:                 10 sec

Threads: 1  Questions: 5  Slow queries: 0  Opens: 107  Flush tables: 1  Open tables: 26  Queries per second avg: 0.500
--------------

```
9. 일반사용자 외부 접속 허용
```bash
$ cd /etc/mysql/mysql.conf.d
$ sed -i 's/bind/# bind/' mysqld.cnf
$ cat mysqld.cnf | grep bind
$ systemctl restart mysql
```
10. 재부팅시 mysqld 자동 실행
```bash
$ update-rc.d mysql defaults
$ reboot
$ mysql -u root -p
```

# 이미지 서버 생성
1. Object Storage 버킷 생성
![image](https://user-images.githubusercontent.com/50297117/97255551-3aef1a80-1854-11eb-950a-e68d34658e0b.png)
![image](https://user-images.githubusercontent.com/50297117/97255953-25c6bb80-1855-11eb-8e0a-6dee0678190d.png)

**Comment by do02reen24** [comment]
# Database Workbench
데이터베이스 및 일반 사용자 생성
```mysql
CREATE DATABASE IF NOT EXISTS issueTracker;
CREATE USER 'id'@'%' IDENTIFIED BY 'password';
```
일반사용자 권한주기
```mysql
GRANT ALL ON issueTracker.* TO 'id'@'%';
FLUSH PRIVILEGES;
```

**Comment by Yejikwon** [comment]
## S3 Browser 실행하기
- 오브젝트 스토리지에 저장된 데이터들에 접근하기 위하여
   많이 사용되는 도구 S3Browesr
![image](https://user-images.githubusercontent.com/13073517/97256998-f4032400-1857-11eb-965d-925fb805c1f5.png)

<hr/>

## 접속 성공 화면 👏
![image](https://user-images.githubusercontent.com/13073517/97257050-21e86880-1858-11eb-9ddd-036602269458.png)
