### ISSUE TITLE
[BE] vscode 확장툴 설정

### ISSUE THREAD

**Issue by yoonwoo123** [boostcamp-2020/IssueTracker-08#51]

**Comment by do02reen24** [comment]
상세 내용은 [Wiki](https://github.com/boostcamp-2020/IssueTracker-08/wiki/Web-%EA%B8%B0%EC%88%A0-%EC%8A%A4%ED%83%9D-%EB%B0%8F-%EC%84%A4%EC%A0%95)에 기록하였습니다.
